project:
  type: website
  output-dir: docs
website:
  site-url: "https://annaduan09.github.io/portfolio" 
  repo-url: https://github.com/annaduan09/portfolio 
  repo-actions: [source]
  navbar:
    search: false
    pinned: true
    left:
      - href: index.qmd
        text: 'Home'
      - href: analysis/TOD.qmd
        text: 'Work Samples'
    right:
        - icon: linkedin
          href: www.linkedin.com/in/annaduan
        - icon: github
          href: https://github.com/annaduan09
        - icon: envelope
          href: mailto:annaduan@sas.upenn.edu

  page-footer:
    left: "&copy; cc-Anna Duan, 2024"
        
format:
  html:
    highlight-style: solarized
    theme: cosmo
